import tkinter
def passwin(desc, passname, password, pemail, note):
    passwin = tkinter.Tk()
    passwin.bind("<Control-s>") # infowriter function here
    passwin.title(desc)
    passwin.geometry("300x610")
    passwin.resizable(True, True)
    passwin.configure(bg="black")
    # copiolet, add entries for the description, username, password, email, and notes 
    desc_label = tkinter.Label(passwin, text="Description: ", font=('Bahnschrift SemiBold SemiConden', 12), bg="black", fg="white")
    desc_label.pack()
    desc_entry = tkinter.Entry(passwin, font=('Century Gothic', 12))
    desc_entry.insert(0, desc)
    desc_entry.pack()
    passname_label = tkinter.Label(passwin, font=('Bahnschrift SemiBold SemiConden', 12), text="Username: ", bg="black", fg="white")
    passname_label.pack()
    passname_entry = tkinter.Entry(passwin, font=('Century Gothic', 12))
    passname_entry.insert(0, passname)
    passname_entry.pack()
    password_label = tkinter.Label(passwin, font=('Bahnschrift SemiBold SemiConden', 12), text="Password: ", bg="black", fg="white")
    password_label.pack()
    password_entry = tkinter.Entry(passwin, font=('Century Gothic', 12))
    password_entry.insert(0, password)
    password_entry.pack()
    pemail_label = tkinter.Label(passwin, font=('Bahnschrift SemiBold SemiConden', 12), text="Email: ", bg="black", fg="white")
    pemail_label.pack()
    pemail_entry = tkinter.Entry(passwin, font=('Century Gothic', 12))
    pemail_entry.insert(0, pemail)
    pemail_entry.pack()
    note_label = tkinter.Label(passwin, font=('Bahnschrift SemiBold SemiConden', 12), text="Notes: ", bg="black", fg="white")
    note_label.pack()
    note_entry = tkinter.Text(passwin, font=('Century Gothic', 12), height=15, width=30)
    note_entry.insert(tkinter.END,note)
    note_entry.pack(pady=10)
    # add a save button
    save_button = tkinter.Button(passwin, text="Save", font=('Bahnschrift SemiBold SemiConden', 12), bg="black", fg="white") # info writer function here
    save_button.pack()
    #passwin.iconbitmap("omward_corral.ico")
    passwin.mainloop()

passwin("secrets.com", "omman", "incorrect123", "no.no@gmail.com", "super secret stuff here lol")